## STATIC CONFIGURATION
log:
  level: DEBUG ## INFO

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
  # websecure:
  #   address: ":443"

# certificatesResolvers:
#   letsEncrypt:
#     acme:
#       tlschallenge: true
#       email: you@example.com
#       storage: /etc/traefik/acme/acme.json
#       caserver: "https://acme-staging-v02.api.letsencrypt.org/directory"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false