# Generated by Django 3.0.4 on 2020-04-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BinaryField()),
                ('exp_month', models.CharField(max_length=4)),
                ('exp_year', models.CharField(max_length=4)),
                ('cvc', models.CharField(max_length=4)),
            ],
        ),
    ]
