# Generated by Django 3.0.4 on 2020-04-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cards', '0002_usercard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='number',
            field=models.CharField(max_length=128),
        ),
    ]
