# Generated by Django 3.0.4 on 2020-04-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cards', '0003_auto_20200420_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='exp_month',
            field=models.CharField(max_length=2),
        ),
    ]
