# Generated by Django 3.0.4 on 2020-04-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cards', '0004_auto_20200420_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='payment_method_id',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
