# Generated by Django 3.0.4 on 2020-04-20 22:58

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_cards', '0005_usercard_payment_method_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='last_four_digits',
            field=models.CharField(default=None, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercard',
            name='number',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
    ]
