# Generated by Django 3.0.4 on 2020-04-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cards', '0006_auto_20200420_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
