# Generated by Django 3.0.4 on 2020-04-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cards', '0007_usercard_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='brand',
            field=models.CharField(default='visa', max_length=24),
            preserve_default=False,
        ),
    ]
