# Generated by Django 3.0.4 on 2020-04-22 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_cards', '0009_usercard_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
