# Generated by Django 3.0.4 on 2020-04-20 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_id', models.CharField(max_length=128)),
                ('setup_intent', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
