# Generated by Django 3.0.4 on 2020-04-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
