# Generated by Django 3.0.4 on 2020-04-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
    ]
