# Generated by Django 3.0.4 on 2020-04-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('DM', 'Delivery Man'), ('CU', 'Customer'), ('SO', 'Store Owner'), ('MA', 'System Manager')], default='CU', max_length=2),
        ),
    ]
