# Generated by Django 3.0.4 on 2020-04-22 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_cards', '0009_usercard_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('charge_id', models.CharField(max_length=128)),
                ('balance_transaction', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_refunded', models.DecimalField(decimal_places=2, max_digits=8)),
                ('failure_code', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_cards.UserCard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
