# Generated by Django 3.0.4 on 2020-04-22 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_charges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercharge',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usercharge',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
    ]
