# Generated by Django 3.0.4 on 2020-04-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_charges', '0002_auto_20200422_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercharge',
            name='paid',
            field=models.BooleanField(default=None),
        ),
    ]
