# Generated by Django 3.0.4 on 2020-04-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_charges', '0003_usercharge_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercharge',
            name='captured',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='usercharge',
            name='currency',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='usercharge',
            name='payment_intent',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='usercharge',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='usercharge',
            name='amount_refunded',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='usercharge',
            name='balance_transaction',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='usercharge',
            name='charge_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='usercharge',
            name='failure_code',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='usercharge',
            name='paid',
            field=models.BooleanField(null=True),
        ),
    ]
