# Generated by Django 3.0.4 on 2020-04-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_charges', '0004_auto_20200422_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercharge',
            old_name='amount_refunded',
            new_name='amount_capturable',
        ),
        migrations.RemoveField(
            model_name='usercharge',
            name='balance_transaction',
        ),
        migrations.RemoveField(
            model_name='usercharge',
            name='captured',
        ),
        migrations.RemoveField(
            model_name='usercharge',
            name='charge_id',
        ),
        migrations.RemoveField(
            model_name='usercharge',
            name='failure_code',
        ),
        migrations.RemoveField(
            model_name='usercharge',
            name='paid',
        ),
        migrations.AddField(
            model_name='usercharge',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='usercharge',
            name='status',
            field=models.CharField(max_length=48, null=True),
        ),
    ]
