# Generated by Django 3.0.4 on 2020-04-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_charges', '0005_auto_20200422_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercharge',
            name='order_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
